<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVdmq1hr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVdmq1hr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVdmq1hr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVdmq1hr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVdmq1hr\appDevDebugProjectContainer([
    'container.build_hash' => 'Vdmq1hr',
    'container.build_id' => 'b45e5f17',
    'container.build_time' => 1613050690,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVdmq1hr');
